name: Make release


on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Prepare source tarball
        run: |
          git clone -b ${{ github.event.release.name }} --depth 1 https://github.com/gaoyaxuan/Minimalist-Web-Notepad-Go Minimalist-Web-Notepad-Go-${{ github.event.release.name }}
          cd Minimalist-Web-Notepad-Go-${{ github.event.release.name }} && go mod tidy && go mod vendor
      - name: Build files
        run: |
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o Minimalist-Web-Notepad-Go.exe
          zip Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-64bit.zip Minimalist-Web-Notepad-Go.exe static/*  ./index.html 
          CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -ldflags '-extldflags "-static"' -o Minimalist-Web-Notepad-Go.exe
          zip Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-32bit.zip Minimalist-Web-Notepad-Go.exe static/*  ./index.html 
          CGO_ENABLED=0 GOOS=windows GOARCH=arm go build -ldflags '-extldflags "-static"' -o Minimalist-Web-Notepad-Go.exe
          zip Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-ARM.zip Minimalist-Web-Notepad-Go.exe static/*  ./index.html 
          CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -ldflags '-extldflags "-static"' -o Minimalist-Web-Notepad-Go.exe
          zip Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-ARM64.zip Minimalist-Web-Notepad-Go.exe static/*  ./index.html 
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-64bit.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -ldflags '-extldflags "-static"' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-32bit.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags '-extldflags "-static"' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-ARM.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags '-extldflags "-static"' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-ARM64.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags '-s -extldflags "-sectcreate __TEXT __info_plist Info.plist"' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_macOS-64bit.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags '-s -extldflags "-sectcreate __TEXT __info_plist Info.plist"' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_macOS-ARM64.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 go build -ldflags '' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_DragonFlyBSD-64bit.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -ldflags '' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_FreeBSD-64bit.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=freebsd GOARCH=arm64 go build -ldflags '' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_FreeBSD-ARM64.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=netbsd GOARCH=386 go build -ldflags '' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_NetBSD-32bit.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 go build -ldflags '' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_NetBSD-64bit.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=netbsd GOARCH=arm64 go build -ldflags '' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_NetBSD-ARM64.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 go build -ldflags '' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_OpenBSD-64bit.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html 
          CGO_ENABLED=0 GOOS=openbsd GOARCH=arm64 go build -ldflags '' -o Minimalist-Web-Notepad-Go
          tar -czvf Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_OpenBSD-ARM64.tar.gz Minimalist-Web-Notepad-Go static/*  ./index.html
      - name: Create checksums.txt
        run: |
          touch Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-64bit.zip >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-32bit.zip >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-ARM.zip >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-ARM64.zip >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-64bit.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-32bit.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-ARM.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-ARM64.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_macOS-64bit.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_macOS-ARM64.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_DragonFlyBSD-64bit.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_FreeBSD-64bit.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_FreeBSD-ARM64.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_NetBSD-32bit.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_NetBSD-64bit.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_NetBSD-ARM64.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_OpenBSD-64bit.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
          sha256sum Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_OpenBSD-ARM64.tar.gz >> Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_checksums.txt
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-64bit.zip
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-32bit.zip
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-ARM.zip
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Windows-ARM64.zip
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-64bit.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-32bit.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-ARM.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_Linux-ARM64.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_macOS-64bit.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_macOS-ARM64.tar.gz 
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_DragonFlyBSD-64bit.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_FreeBSD-64bit.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_FreeBSD-ARM64.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_NetBSD-32bit.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_NetBSD-64bit.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_NetBSD-ARM64.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_OpenBSD-64bit.tar.gz
            Minimalist-Web-Notepad-Go_${{ github.event.release.name }}_OpenBSD-ARM64.tar.gz